Azure/Azure-Proactive-Resiliency-Library

.github/ISSUE_TEMPLATE/bug-report---.md
.github/ISSUE_TEMPLATE/feature-request---.md
.github/ISSUE_TEMPLATE/general-question-feedback----.md
.github/PULL_REQUEST_TEMPLATE.md
.github/actions-config/mlc_config.json
.github/fabircbot.json
.github/linters/.markdown-lint.yml
.github/workflows/code-review.yml
.github/workflows/hugo-build-pr-check.yml
.github/workflows/hugo-site-build.yml
README.md
SECURITY.md
SUPPORT.md

- PR Template
- Issue Templates
- FabricBot
- PR Tests/Workflows

Repo Hygiene Additions 

---

docs/archetypes/service-bundle/_index.md
docs/content/services/compute/virtual-machines/_index.md

Small changes to VM files.
- [ x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [ x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [ x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

vmupdates6

---

docs/archetypes/service-bundle/_index.md
docs/content/_index.md
docs/content/services/compute/virtual-machines/_index.md

Column Changes for ARG & Term Definition
1. Closes [AB#27729](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/27729)
None

Column Changes for ARG & Term Definition

---

docs/content/services/compute/virtual-machines/_index.md

1. Updating VMs ARG Table
- [ x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [x ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

Updating VMs ARG Table (#20)

---

docs/content/services/networking/expressroute-gateway/_index.md
docs/content/services/networking/expressroute-gateway/code/exrgw-1/exrgw-1.kql
docs/content/services/networking/expressroute-gateway/code/exrgw-2/exrgw-2.kql
docs/content/services/networking/expressroute-gateway/code/exrgw-3/exrgw-3.kql
docs/content/services/networking/expressroute-gateway/code/exrgw-4/exrgw-4.kql
docs/content/services/networking/expressroute-gateway/code/exrgw-5/exrgw-5.kql

APRL guidance for ExpressRoute Gateway
1. Adds section under Network for ExpressRoute Gateway
- [x ] Updated relevant and associated documentation …

Expressroute gateway - initial PR

---

docs/content/services/networking/expressroute-circuits/_index.md
docs/content/services/networking/expressroute-circuits/code/exrct-1/exrct-1.kql
docs/content/services/networking/expressroute-circuits/code/exrct-3/exrct-3.kql
docs/content/services/networking/expressroute-circuits/code/exrct-4/exrct-4.kql
docs/content/services/networking/expressroute-circuits/code/exrct-5/exrct-5.kql
docs/content/services/networking/expressroute-circuits/code/exrct-7/exrct-7.kql
docs/content/services/networking/vpn-gateway/_index.md

Partial update for ExpressRoute circuit ARG queries

Excrt arg queries

---

docs/content/services/compute/virtual-machines/code/vm-6/vm-6.kql

1. Query for checking data disk is incorrect. Currently it checks whether we have data disk array size as 1, which should be zero (i.e. < 1)

Query bug fix

---

docs/content/services/networking/general-networking/_index.md
docs/content/services/networking/general-networking/code/nw-1/nw-1.kql
docs/content/services/networking/general-networking/code/nw-2/nw-2.kql
docs/content/services/networking/general-networking/code/nw-3/nw-3.kql
docs/content/services/networking/general-networking/code/nw-4/nw-4.kql
docs/content/services/networking/general-networking/code/nw-5/nw-5.kql

Updating Recommendations for General networking
1. *Updating Recommendations for General networking*
NA

Updating Recommendations for General networking

---

docs/content/services/networking/expressroute-circuits/_index.md
docs/content/services/networking/expressroute-circuits/code/erc-5/erc-5.kql
docs/content/services/networking/expressroute-circuits/code/erc-6/erc-6.kql

Added 3 tested/validated ARG queries for ExpressRoute circuits
1. Added tested/validatedARG query for ERC-1, ERC-5 and ERC-6

Added 3 tested/validated ARG queries for ExpressRoute circuits

---

docs/content/services/compute/virtual-machine-scale-sets/code/vmss-1/vmss-1.kql
docs/content/services/compute/virtual-machines/code/vm-2/vm-2.kql

Correction/update for KQL used for VM/VMSS
1. Fixes #47 KQL in https://azure.github.io/Azure-Proactive-Resiliency-Library/services/compute/virtual-machines/#vm-2---deploy-virtual-machines-across-availability-zones
2. Added KQL in https://azure.github.io/Azure-Proactive-Resiliency-Library/services/compute/virtual-machine-scale-sets/#vmss-1---deploy-using-flexible-scale-set-instead-of-simple-virtual-machines
N/A

KQL update for compute

---

docs/content/services/web/_index.md
docs/content/services/web/app service plan/_index.md
docs/content/services/web/app service plan/code/asp-1/asp-1.kql
docs/content/services/web/app service plan/code/asp-2/asp-2.kql
docs/content/services/web/app service plan/code/asp-5/asp-5.kql
docs/content/services/web/app service/_index.md
docs/content/services/web/app service/code/app-2/app-2.kql

ADO: 27253
1. App Service Plan recommendations 
2. App Service [started/ work in progress]
- [ x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [ x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [ x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [ x] …

Added App Service Plan recommendations and started with App Service 

---

docs/content/services/storage/storage-Account/_index.md
docs/content/services/storage/storage-Account/code/st-1/st-1.kql
docs/content/services/storage/storage-Account/code/st-2/st-2.kql
docs/content/services/storage/storage-Account/code/st-3/st-3.kql
docs/content/services/storage/storage-Account/code/st-4/st-4.kql
docs/content/services/storage/storage-Account/code/st-5/st-5.kql
docs/content/services/storage/storage-Account/code/st-6/st-6.kql
docs/content/services/storage/storage-Account/code/st-7/st-7.kql
docs/content/services/storage/storage-Account/code/st-8/st-8.kql
docs/content/services/storage/storage-Account/code/st-9/st-9.kql

Update to Azure Resource graph query which had a bug 
Update script (Powershell) which was marked as under-development before.
st-1.kql was not working

Update to  script/queries for storage account

---

docs/content/services/networking/virtual-networks/_index.md
docs/content/services/networking/virtual-networks/code/vnet-1/vnet-1.kql
docs/content/services/networking/virtual-networks/code/vnet-2/vnet-2.kql
docs/content/services/networking/virtual-networks/code/vnet-3/vnet-3.kql
docs/content/services/security/key-vault/code/kv-1/kv-1.kql
docs/content/services/security/key-vault/code/kv-2/kv-2.kql
docs/content/services/security/key-vault/code/kv-3/kv-3.kql
docs/content/services/security/key-vault/code/kv-4/kv-4.kql
docs/content/services/security/key-vault/code/kv-5/kv-5.kql

Pull Request to Update ARG queries for Virtual network and Key Vault in the suggested format.
1. Update ARG query for Virtual Network
2. Update ARG query for Key Vault
NA

Update ARG queries for Virtual network and Key Vault in the suggested format

---

docs/content/services/compute/image-templates/_index.md
docs/content/services/compute/image-templates/code/it-2/it-2.kql

[AB#30167](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/30167)
Adding recommendations and KQL queries for Image Template resource
1. Adding recommendations and KQL queries for Image Template resource
1. None as this was just content changes and validated within local Hugo server

Image Templates Recommendations/Queries initial commits

---

.vscode/settings.json
docs/content/services/integration/event-grid/_index.md
docs/content/services/integration/event-grid/code/evg-1/evg-1.ps1
docs/content/services/integration/event-grid/code/evg-2/evg-2.ps1
docs/content/services/integration/event-grid/code/evg-3/evg-3.kql
docs/content/services/networking/route-table/_index.md
docs/content/services/networking/route-table/code/rt-1/rt-1.ps1
docs/content/services/networking/route-table/code/rt-2/rt-2.ps1

Created Service section for Event Grid along with 3 recommendations.
1. EVG-1 - Configure Diagnostic Settings for all Azure Resources (PowerShell Script)
2. EVG-2 - Configure Dead-letter to save events that cannot be delivered (PowerShell Script)
3. EVG-3 - Configure Private Endpoints (ARG)
None

Event Grid Recommendations

---

docs/content/services/database/sqldb/_index.md

Added SQLDB-7
1. Added another SQL DB recommendation for testing failovers. 
1. None, just added new recommendation to existing service

Added SQLDB-7 recommendation

---

docs/archetypes/service-bundle/_index.md
docs/content/services/compute/virtual-machines/_index.md
docs/content/services/compute/virtual-machines/code/vm-1/vm-1.kql
docs/content/services/compute/virtual-machines/code/vm-2/vm-2.kql
docs/content/services/compute/virtual-machines/code/vm-21/vm-21.kql
docs/content/services/compute/virtual-machines/code/vm-22/vm-22.kql
docs/content/services/compute/virtual-machines/code/vm-3/vm-3.kql
docs/content/services/compute/virtual-machines/code/vm-4/vm-4.kql

vm-updates

---

docs/content/services/web/web-app/code/cm-1/cm-1.azcli
docs/content/services/web/web-app/code/cm-1/cm-1.kql
docs/content/services/web/web-app/code/cm-1/cm-1.ps1
docs/content/services/web/web-app/code/cm-2/cm-2.azcli
docs/content/services/web/web-app/code/cm-2/cm-2.kql
docs/content/services/web/web-app/code/cm-2/cm-2.ps1

updating web-app

---

docs/content/services/networking/traffic-manager/code/traf-1/traf-1.kql
docs/content/services/networking/traffic-manager/code/traf-2/traf-2.kql
docs/content/services/networking/traffic-manager/code/traf-3/traf-3.kql
docs/content/services/networking/traffic-manager/code/traf-4/traf-4.kql
docs/content/services/networking/traffic-manager/code/traf-5/traf-5.kql
docs/content/services/web/web-app/code/cm-1/cm-1.azcli
docs/content/services/web/web-app/code/cm-1/cm-1.kql
docs/content/services/web/web-app/code/cm-1/cm-1.ps1
docs/content/services/web/web-app/code/cm-2/cm-2.azcli
docs/content/services/web/web-app/code/cm-2/cm-2.kql
docs/content/services/web/web-app/code/cm-2/cm-2.ps1

Adding recommendationId to Traffic Manager queries

---

docs/content/services/monitoring/application-insights/_index.md
docs/content/services/monitoring/application-insights/code/appi-1/appi-1.kql
docs/content/services/monitoring/application-insights/code/ins-1/ins-1.kql

1./monitoring/application insights/ins-1

added application insights rule ins-1

---

docs/content/services/web/signalr/_index.md
docs/content/services/web/signalr/code/sigr-1/sigr-1.azcli
docs/content/services/web/signalr/code/sigr-1/sigr-1.kql
docs/content/services/web/signalr/code/sigr-1/sigr-1.ps1

[AB#29871](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/29871)
Adding SignalR service and recommendation for zone redundancy (sigr-1)
1. Recommendation sigr-1 for zone redundancy
2. ARG query for sigr-1
1. None

add SignalR recommendation sigr-1

---

docs/content/services/monitoring/application-insights/code/appi-1/appi-1.kql

1. Monitoring/ApplicationInsights KQL

Update typo in appi-1.kql

---

docs/content/services/compute/virtual-machine-scale-sets/_index.md

Update VMSS-8 to include link to zonal expansion document
1. Add a link in the resources section for VMSS-8
1. None

add VMSS-8 link to public doc

---

docs/content/services/integration/event-hub/_index.md
docs/content/services/integration/event-hub/code/evhns-1/evhns-1.azcli
docs/content/services/integration/event-hub/code/evhns-1/evhns-1.kql
docs/content/services/integration/event-hub/code/evhns-1/evhns-1.ps1

[AB#29816](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/29816)
Adding Event Hub service and recommendation for zone redundancy (evhns-1)
1. Recommendation evhns-1 for zone redundancy
2. ARG query for evhns-1
1. None

add event hub recommendation evhns-1

---

.github/actions-config/mlc_config.json
.github/workflows/code-review.yml

Fixes markdown lint errors by removing valid MS opensource links from tests.
1. Adds back opensource check for other lint test not associated to markdown links
2. Fixes markdown lint errors by removing valid MS opensource …

Fix-linting

---

docs/content/services/networking/virtual-networks/code/vnet-1/vnet-1.kql
docs/content/services/networking/virtual-networks/code/vnet-2/vnet-2.kql
docs/content/services/networking/virtual-networks/code/vnet-3/vnet-3.kql
docs/content/services/security/key-vault/code/kv-1/kv-1.kql
docs/content/services/security/key-vault/code/kv-2/kv-2.kql
docs/content/services/security/key-vault/code/kv-3/kv-3.kql

Updating all queries for Virtual network and Key vault for adding tags
Fixes [AB#31170](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/31170)
Fixes [AB#31180](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/31180)
Updating all queries for Virtual network and Key vault for adding tags
NA

Updating all queries for Virtual network and Key vault for adding tags

---

docs/content/services/integration/api-management/_index.md
docs/content/services/integration/api-management/code/apim-1/apim-1.kql
docs/content/services/integration/api-management/code/apim-2/apim-2.kql
docs/content/services/networking/load-balancer/_index.md

API Management service: Added new service category with 2 recommendations.
[AB#29874](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/29874)
[AB#31532](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/31532)
1. Fixes: LB-4 State from GA to Preview
2. Add: APIM-1 - Migrate API Management services to Premium SKU to support Availability Zones
3. Add: APIM-2 - Enable Availability Zones on Premium API Management instances
N/A

Apim services

---

docs/content/contributing/_index.md

Contribution guide is missing requirement to have comments describing what info the query provides
[AB#31666](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/31666)
1. Adds to contribution guide to include missing requirement to have comments describing what info the query provides
2. Adds clarification note that column names must match exactly as they are listed in the table within the contribution guide
N/A

Adding comment requirements for kql queries

---

docs/content/services/networking/expressroute-circuits/_index.md
docs/content/services/networking/expressroute-circuits/code/erc-1/erc-1.kql
docs/content/services/networking/expressroute-circuits/code/erc-2/erc-2.kql
docs/content/services/networking/expressroute-circuits/code/erc-3/erc-3.kql
docs/content/services/networking/expressroute-circuits/code/erc-4/erc-4.kql
docs/content/services/networking/expressroute-circuits/code/erc-5/erc-5.kql
docs/content/services/networking/expressroute-circuits/code/erc-6/erc-6.kql
docs/content/services/networking/expressroute-circuits/code/erc-7/erc-7.kql
docs/content/services/networking/expressroute-circuits/code/erc-8/erc-8.kql
docs/content/services/networking/expressroute-circuits/code/erc-9/erc-9.kql

Updates to APRL ERG section, updated all queries
[AB#31164](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/31164)
Updated all queries to match format
Updated _index.md to include Impact column

APRL ERC updates for Oct 2023

---

.github/policies/resource-managment.yml
docs/content/services/compute/virtual-machines/code/vm-5/vm-5.kql

Need additional automation to assist with PR/issue management at scale.
[AB#32345](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/32345)
1. Adds a variety of policies for managing pull request and issue contributions. 
1. None

Adds GitHub policies for managing contributions.

---

docs/content/services/networking/web-application-firewall/_index.md
docs/content/services/networking/web-application-firewall/code/waf-1/waf-1.kql
docs/content/services/networking/web-application-firewall/code/waf-2/waf-2.kql
docs/content/services/networking/web-application-firewall/code/waf-3/waf-3.kql
docs/content/services/networking/web-application-firewall/code/waf-4/waf-4.kql
docs/content/services/networking/web-application-firewall/code/waf-6/waf-6.kql
docs/content/services/networking/web-application-firewall/code/waf-7/waf-7.kql
docs/content/services/networking/web-application-firewall/code/waf-8/waf-8.kql

…ered.
Updates to APRL WAF section to fix merge conflict from Oct 2023
Validated locally using hugo.
[AB#31327](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/31327)
[AB#31328](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/31328)
Removed original WAF-1, duplicate of AGW-3
Removed original WAF-2, duplicate of AFD-10
Removed original WAF-7. This was incorporated into guidance for the now WAF-3 and WAF-4.
Updated content of all WAF .kql files with "// cannot-be-validated-with-arg"
Minor grammar/syntax updates in WAF's _index.md

APRL WAF updates to fix merge conflict from Oct 2023

---

docs/content/services/networking/expressroute-gateway/_index.md
docs/content/services/networking/expressroute-gateway/code/erg-1/erg-1.kql
docs/content/services/networking/expressroute-gateway/code/erg-3/erg-3.kql

Updates to APRL ERG section to fix merge conflict from Oct 2023
Validated locally using hugo.
[AB#31172](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/31172)
ExpressRoute Gateway
Updated all queries to standardized format
Minor updates to _index.md for ERG

APRL ERG updates to fix merge conflicts from Oct 2023

---

docs/content/services/web/app-service-plan/_index.md

Fixed duplicated code blocks for the ASP index page.
- None
1. Removes duplicated code blocks.
2. Adds missing sub-headers `Resource Graph Query/Scripts`
- None

Fix duplicated code blocks for ASP

---

docs/content/services/networking/network-security-group/_index.md
docs/content/services/networking/network-security-group/code/nsg-4/nsg-4.kql

Added an ARG query for NSG-4.
- None
1. Adds an ARG query for NSG-4.
2. Updates the `ARG Query Available` column of NSG-4 in the _index.md
- None

Add NSG-4 query

---

docs/content/services/networking/firewall/_index.md

Simple table update.
1. AFW table update.
N/A

Update _index.md AFW Query status update

---

docs/content/services/networking/network-security-group/code/nsg-4/nsg-4.kql.fix

Removed the `nsg-4.kql.fix` file because there is the [fixed KQL file](https://github.com/Azure/Azure-Proactive-Resiliency-Library/blob/5a2e835434ae45b70d4956914358efe83bc4a0db/docs/content/services/networking/network-security-group/code/nsg-4/nsg-4.kql) currently. The fixed query marged on #188.
- #188
1. Removes `nsg-4.kql.fix` file.
- None

Remove nsg-4.kql.fix file

---

docs/content/services/networking/application-gateway/_index.md

Adjusting the wording of AGW-1 to align better to the public documentation recommendations for AppGW v2.
Devops Work Item: https://dev.azure.com/CSUSolEng/Guidance%20-%20AZ%20Migration/_sprints/backlog/Guidance%20-%20AZ%20Migration%20Team/Guidance%20-%20AZ%20Migration/Germanium/202401?workitem=31565
1. AGW-1

Agw-1 wording adjustment

---

docs/content/services/networking/expressroute-gateway/_index.md
docs/content/services/networking/expressroute-gateway/code/ergw-4/ergw-4.kql

Removed ERGW-4 per user story 32526
AB#32526
1. Removes guidance ERGW-4
- [x ] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to …

Removed ERGW-4 guidance 

---

docs/content/services/networking/expressroute-circuits/_index.md

The wording for ERC-2 was not clearly stated and caused confusion amongst the reader. This change is to make the recommendation clear. 
1. https://dev.azure.com/CSUSolEng/Azure%20Infra%20Networking/_workitems/edit/32666/

Clarifies wording for ERC-2

---

docs/content/services/networking/expressroute-gateway/_index.md
docs/content/services/networking/expressroute-gateway/code/ergw-4/ergw-4.kql

Added guidance for new ERGW-4.
AB#32703
1. Guidance for ERGW-4 - Configure diagnostic logs and alerts for ExpressRoute virtual network gateway 
- [x ] Performed testing and …

Added new guidance ERGW-4

---

docs/content/services/database/db-for-postgresql/code/psql-1/psql-1.kql

added tags to postgresql file (1/1)
[AB#32761](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/32761)
https://dev.azure.com/CSUSolEng/Well-Architected%20Framework/_workitems/edit/32761
1. psql-1.kql

Added tags to psql-1.kql

---

docs/content/services/compute/image-templates/_index.md
docs/content/services/compute/image-templates/code/it-2/it-2.kql
docs/content/services/compute/image-templates/code/it-2/it-2.kql.fix

Fixed the Image Gallery 2 query
[AB#32796](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/32796)
1. adds the it-2 query
none

fixed it-2

---

docs/content/services/networking/expressroute-connection/_index.md
docs/content/services/networking/expressroute-connection/code/ercon-1/ercon-1.kql

New APRL section for ExpressRoute Connection with 1 guidance entry
AB#32874
1. Adds a new APRL section for ExpressRoute Connection
2. Adds 1 new section of guidance

New APRL section for ExpressRoute Connection with 1 guidance entry

---

docs/content/services/networking/expressroute-direct/_index.md
docs/content/services/networking/expressroute-direct/code/erd-1/erd-1.kql
docs/content/services/networking/expressroute-direct/code/erd-2/erd-2.kql
docs/content/services/networking/expressroute-direct/code/erd-3/erd-3.kql

New APRL section for ExpressRoute Direct with 3 guidance entries
AB#32875
1. Adds a new APRL section for ExpressRoute Direct
2. Adds 3 new sections of guidance

New APRL section for ExpressRoute Direct with 3 guidance entries

---

docs/content/services/networking/expressroute-traffic-collector/_index.md
docs/content/services/networking/expressroute-traffic-collector/code/ertc-1/ertc-1.kql

Create new ERTC section in APRL for ExpressRoute Traffic Collector
Add the following guidance:
ERTC-1 – Ensure ExpressRoute Traffic Collector is enabled and configured to get deeper insights of you network traffic
AB#32876
1. Adds new APRL section for ExpressRoute Traffic Collector
2. Adds ERTC-1 guidance to that new section

New guidance section for ExpressRoute Traffic Collector

---

docs/content/services/integration/event-grid/code/evg-3/evg-3.kql

added tags column to Event Grid ARG queries
[AB#32912](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/32912)
1. evg-3.kql

Add tags to Event Grid ARG Queries

---

docs/content/services/integration/api-management/code/apim-1/apim-1.kql
docs/content/services/integration/api-management/code/apim-2/apim-2.kql

Added tags to 2/2 API Management Queries in APRL
[AB#32859](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/32859)
1. apim-1.kql
2. apim-2.kql

Add tags to API Management Queries

---

docs/content/services/networking/expressroute-circuits/_index.md

Updated wording for ERC-5 to incorporate AMBA references
AB#32877
1. Updated wording for ERC-5 to incorporate AMBA references
2. Minor tweaks to language for other ERC guidance

Updated wording for ERC-5 to incorporate AMBA references

---

docs/themes/ace-documentation/layouts/partials/head.html

Update head.html to add Clarity insights

Update head.html to add Clarity insights

---

docs/content/contributing/_index.md

Add list of allowed recommendation categories and descriptions to contribution guide
None
1. List of categories to contribution guide
1. None

add category guidance to contribution guide

---

docs/content/contributing/_index.md

Added guidance to contributor guide for using only 1 category per recommendation
N/A
1. Added guidance to contributor guide for using only 1 category per recommendation
- [ X] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [ X] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [X ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [ X] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

Added guidance to contribution guide for category

---

docs/content/services/management/management-group/code/mg-1/mg-1.kql
docs/content/services/migration/azure-backup/code/bk-1/bk-1.kql
docs/content/services/monitoring/application-insights/code/appi-1/appi-1.kql

adding tags to ARG queries
[AB#33059](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/33059)
[AB#33060](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/33060)
[AB#33062](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/33062)
1. mg-1.kql
2. bk-1.kql
3.  appi-1.kql

add tags to MG, backups, app insights

---

docs/content/privacy/_index.md

Added privacy page for the integration of Clarity.
NA
1. Adds new privacy page
None

Feature: Added privacy page

---

docs/content/services/storage/azure-netapp-files/_index.md
services-abbreviations.csv

ANF minor updates based on ANF technical writer Arnt de Gier's feedback including "NetApp" instead of "Netapp" and networking feature"s" to match with the portal naming.
1. "NetApp" instead of "Netapp"
2. networking …

Update ANF minor changes

---

docs/content/services/monitoring/service-health-alerts/_index.md
docs/content/services/monitoring/service-health-alerts/code/ala-1/ala-1.kql

Add recommendation for Service Health alerts
None
1. Add service health service
2. Add service health recommendation ALA-1
3. Add placeholder kql query
1. None

add service health recommendation

---

docs/content/services/database/db-for-postgresql/_index.md
docs/content/services/database/db-for-postgresql/code/psql-1/psql-1.azcli
docs/content/services/database/db-for-postgresql/code/psql-1/psql-1.ps1
docs/content/services/database/db-for-postgresql/code/psql-2/psql-2.kql

Add DB for PostgreSQL recommendation
None
1. Add recommendation psql-2
2. Add placeholder kql file
1. None

add db for postgresql recommendation

---

docs/content/services/database/db-for-mysql/_index.md
docs/content/services/database/db-for-mysql/code/mysql-1/mysql-1.kql
docs/content/services/database/db-for-mysql/code/mysql-2/mysql-2.kql
services-abbreviations.csv

Add DB for MySQL recommendations
None
1. Add DB for MySQL service
2. Add recommendations MYSQL-1 and MYSQL-2, and placeholder kql files
3. Add mysql to services-abbreviations.csv
1. None

Add DB for MySQL recommendations

---

docs/content/services/specialized-workloads/azure-vmware-solution/_index.md
docs/content/services/specialized-workloads/azure-vmware-solution/avs-1.kql
docs/content/services/specialized-workloads/azure-vmware-solution/code/avs-3/avs-3.kql
docs/content/services/specialized-workloads/azure-vmware-solution/code/avs-4/avs-4.kql
docs/content/services/specialized-workloads/azure-vmware-solution/code/avs-5/avs-5.kql
docs/content/services/specialized-workloads/azure-vmware-solution/code/avs-6/avs-6.kql

This pull requests adds resource graph queries for AVS-3, AVS-4, AVS-5, and AVS-6.  It also makes minor changes to the recommendation text. (Cleans up some grammar and removes random double spaces).  Finally, it removes the avs-1.kql file that erroneously got moved into the root of the AVS folder.
- To associate an ADO Work Item, use the key word `AB#` succeeded with the [ADO Work Item ID](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull- …

avs kql updates

---

docs/content/services/networking/load-balancer/_index.md

edits for LB resiliency guidance

Update _index.md for Load Balancer

---

docs/content/services/specialized-workloads/azure-vmware-solution/_index.md
docs/content/services/specialized-workloads/azure-vmware-solution/code/avs-4/avs-4.kql
docs/content/services/specialized-workloads/azure-vmware-solution/code/avs-5/avs-5.kql
docs/content/services/specialized-workloads/azure-vmware-solution/code/avs-6/avs-6.kql

Quality Review by PG

---

docs/content/services/storage/storage-Account/_index.md

Fixed ST-2 guidance text and resource URL.
None
1. Fixes the ST-2 guidance text.
2. Fixes the link text in the ST-2 resource section.
3. Adds URL of document on this topic to the ST-2 resource section.
None
- The document build succeeded on my local machine.

Fix ST-2 guidance text and resource URL

---

docs/content/services/compute/virtual-machines/_index.md
docs/content/services/compute/virtual-machines/code/vm-1/vm-1.kql

Update guidance and add query for VM-1
None
1. Update guidance for VM-1
2. Update resource links for VM-1
3. Add ARG query for VM-1
1. None

update vm-1 guidance and query

---

docs/content/services/compute/virtual-machines/_index.md
docs/content/services/management/resource-group/_index.md
docs/content/services/networking/traffic-manager/_index.md
docs/content/services/specialized-workloads/sap-on-azure/_index.md

Rosanto - fixing titles of sap, vm, traf, rg which had "" or - in the title

Rosanto - fixing titles of sap, vm, traf, rg which had "" or - in the title

---

docs/content/services/networking/vpn-gateway/_index.md

Minor correction to sku references for VPNG-2 - Plan for Active-Active mode
N/A
1. Added standard sku reference to  VPNG-2 - Plan for Active-Active mode recommendation guidance
1. None

Guidance Update for VPNG-2

---

docs/content/services/compute/virtual-machines/_index.md

Update VM-23 recommendation details impact to match summary table value
None
1. Change VM-23 recommendation detail impact value to High
1. None

update vm-23 impact value

---

docs/content/services/ai-ml/databricks/_index.md
docs/content/services/database/sqldb/_index.md
docs/content/services/iot/iot-hub/_index.md
docs/content/services/networking/network-security-group/_index.md

Update recommendation impact misalignment between recommendation details and recommendation summary table
None
1. update dbw-3, sqldb-5, ioth-4, and nsg-3
1. None

update misaligned impact

---

docs/content/services/networking/public-ip/_index.md
docs/content/services/networking/public-ip/code/pip-3/pip-3.kql

Added a new recommendation PIP-3 for upgradeable Basic SKU public IP addresses.
None
1. Adds a new recommendation PIP-3.
None

Add PIP-3 - Upgrade Basic SKU public IP addresses to Standard SKU

---

docs/content/services/networking/public-ip/_index.md
docs/content/services/networking/public-ip/code/pip-1/pip-1.kql

Improved PIP-1 query.
None
1. Added [Global tier](https://learn.microsoft.com/en-us/azure/virtual-network/ip-services/public-ip-addresses#sku) consideration.
2. Added tags column.
None
- [Test case used for screenshots](https://github.com/tksh164/aprl-testing/tree/main/services/networking/public-ip/test/pip-1)

Improve PIP-1 query

---

docs/content/services/networking/vpn-gateway/_index.md

Making minor updates to recommendations for VPN
N/A
1. Making minor updates to recommendations for VPN
1. None

Updated VPN recommendations

---

CODEOWNERS
docs/content/services/container/aks/_index.md

Update broken link for AKS-5 resources section and codeowners file issue due to auto-format
None
1. Update link to new url
2. Fix codeowners file
1. None

update aks-5 broken link and fix codeowners file

---

docs/content/services/networking/expressroute-gateway/code/ergw-7/ergw-7.kql

Added ARG query for ERGW-7
1. Adds ARG query for ERGW-7
Fixes: [34290](https://dev.azure.com/CSUSolEng/Azure%20Infra%20Networking/_workitems/edit/34290)
- [ x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [ x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [ x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [ x] Ensured PR tests are passing
- [x ] Performed testing …

ERGW-7 ARG

---

docs/content/services/compute/virtual-machines/_index.md

Update VM-5 Guidance and Resources.
Previous guidance is not clear on why customer should use managed disk. Updated that with EoS info.
1. Update "VM-5 - Use Managed Disks for VM disks" Guidance and Resources.
Previous …

Update VM-5 guidance and resources

---

docs/content/services/networking/public-ip/_index.md

Correcting recommendation wording for PIP-1
- [ X] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [ X] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [X ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [ X] Ensured PR tests are passing

Recommendation Correction for PIP-1

---

docs/content/services/ai-ml/databricks/_index.md

The guidance for DBW-6 is incorrect. Updated it to align with azure doc.
1. The guidance for DBW-6 is incorrect. Updated it to align with azure doc.
N/A

Update DBW-6 _index.md

---

docs/content/services/networking/application-gateway/_index.md

Remove AGW-7 from Index page.  Code directory for AGW-7 and kql files left in repo.  Verified via local hugo build that links for AGW-6 and AGW-8 still work as expected.
AB#34284
https://dev.azure.com/CSUSolEng/Azure%20Infra%20Networking/_workitems/edit/34284/
1. Removes AGW-7 from the list of recommendations
None

Updated AGW Page to remove AGW-7

---

docs/content/well-architected/5-monitor/_index.md

Add recommendation wamn-5
[AB#33214](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/33214)
1. Adds recommendation wamn-5
1. None

Add recommendation wamn-5

---

docs/content/services/migration/azure-backup/_index.md

Azure Backup APRL verified by PM Nikhil Sarode
1. Update to be verified
2. Remove "en-us" in resource links
N/A

Azure Backup APRL verified by PM Nikhil Sarode

---

docs/content/services/compute/site-recovery/code/asr-1/asr-1.kql

Per https://csusoleng.visualstudio.com/Well-Architected%20Framework/_workitems/edit/29842 CSA is not able to find a way to check through ARG.
"For this recommendation, I have created below ARG query which Identifies the Recovery Static IP address configured for the VMs and whether it is included in the IP address range configured for the recovery subnet. However, it doesn't check whether the particular Static IP is available in to be assigned in the subnet. I couldn't find how to create a query around this."
- To associate a GitHub Issue, use a [key word](https://docs.github.com/en/issues/tracking-your-work-with-issues/ …

Update asr-1.kql as cannot be validated

---

docs/content/services/networking/network-security-group/_index.md

Remove incorrect NSG query links from NSG index file
None
1. Removes incorrect query links from nsg-1 and nsg-3
1. None

Remove incorrect NSG query links

---

docs/content/services/storage/azure-netapp-files/code/anf-6/anf-6.kql
docs/content/services/storage/azure-netapp-files/code/anf-7/anf-7.kql

remove incorrect column name from anf queries
None
1. remove incorrect column name from anf queries

remove incorrect column name from anf queries

---

docs/content/services/specialized-workloads/azure-virtual-desktop/_index.md
docs/content/services/specialized-workloads/azure-virtual-desktop/code/avd-38/avd-38.kql

Update AVD-38 to AVD-37
1. Fixes AVD-38 numbering to AVD-37

Update AVD-38 to AVD-37

---

docs/content/services/specialized-workloads/azure-vmware-solution/_index.md

AVS Updated Monitoring configure to High.

AVS Updated Monitoring configure to High.md

---

docs/content/services/compute/virtual-machines/_index.md

VS 23 & 24 Status updated with PG sign off

VS 23 & 24 Status updated with PG sign off Update _index.md

---

docs/themes/ace-documentation/layouts/partials/head.html

add header redirect
