- docs/config.toml
- docs/themes/ace-documentation/layouts/_default/baseof.html
As suggested in #8 this PR adds a back to top button to all pages without requiring any contributor to add code to their `.md` file via the power of hugo 😎 and also disables the TOC on right
1. Add back to top button to all pages
2. Disable TOC on right
None
> Add back to top button to all pages & disable TOC on right

- docs/content/services/compute/virtual-machines/_index.md
There is a filename error in one of the virtual-machines recommendations that is not allowing Hugo server to run. The kql file for vm-14 is pointing to a file vm-4.kql and then causing a "The system cannot find the path specified."
1. Fixes the filename error from vm-4.kql to vm-14.kql in the vm-14 folder
None
- [ x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [ x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [x ] Ensured my code/branch is up-to-date with the latest …
> Fix filename mismatch for vm-14 klq file

- docs/content/services/database/cosmosdb/_index.md
- docs/content/services/database/cosmosdb/code/cosmos-1/cosmos-1.kql
- docs/content/services/database/cosmosdb/code/cosmos-2/cosmos-2.kql
- docs/content/services/database/cosmosdb/code/cosmos-3/cosmos-3.kql
- docs/content/services/database/cosmosdb/code/cosmos-4/cosmos-4.kql
- docs/content/services/database/cosmosdb/code/cosmos-5/cosmos-5.kql
- docs/content/services/database/sqldb/_index.md
This PR adds service guidance for Azure Cosmos DB. The guidance has been reviewed and approved by engineering.
Related ADO item id: 27706
1. Adds service guidance for Azure Cosmos DB
None
> added Cosmos DB guidance

- docs/content/services/web/app service/_index.md
- docs/content/services/web/app service/code/app-2/app-2.kql
- docs/content/services/web/app service/code/app-2/app-5.kql
Add recommendations for App Service ADO: 27253
1. Add recommendations for App Service
> Add recommendations for App Service ADO: 27253

- docs/content/services/container/azure-container-registry/_index.md
- docs/content/services/container/azure-container-registry/code/cr-1/cr-1.kql
- docs/content/services/container/azure-container-registry/code/cr-12/cr-12.kql
- docs/content/services/container/azure-container-registry/code/cr-2/cr-2.kql
- docs/content/services/container/azure-container-registry/code/cr-3/cr-3.kql
- docs/content/services/container/azure-container-registry/code/cr-6/cr-6.kql
- docs/content/services/container/azure-container-registry/code/cr-7/cr-7.kql
- docs/content/services/container/azure-container-registry/code/cr-8/cr-8.kql
- docs/content/services/container/azure-container-registry/code/cr-9/cr-9.kql
- docs/themes/ace-documentation/README.md
[AB#30170](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/30170)
Adding recommendations and KQL queries for Azure Container Registry
1. Adding recommendations and associated KQL queries (for Azure Container Registry
1. Only adding content and tested within local Hugo environment
> Azure Container Registry Recommendations/Queries

- docs/content/services/storage/azure-netapp-files/_index.md
- docs/content/services/storage/azure-netapp-files/code/anf-1/anf-1.kql
- docs/content/services/storage/azure-netapp-files/code/anf-2/anf-2.kql
- docs/content/services/storage/azure-netapp-files/code/anf-3/anf-3.kql
- docs/content/services/storage/azure-netapp-files/code/anf-4/anf-4.kql
- docs/content/services/storage/azure-netapp-files/code/anf-5/anf-5.kql
- docs/content/services/storage/azure-netapp-files/code/anf-6/anf-6.kql
- docs/content/services/storage/azure-netapp-files/code/anf-7/anf-7.kql
- docs/content/services/storage/azure-netapp-files/code/anf-8/anf-8.kql
Recommendations for Azure Netapp Files
1. Add Recommendations for Azure Netapp Files
NA
> Recommendations for Azure Netapp Files

- docs/content/services/compute/virtual-machines/_index.md
- docs/content/services/compute/virtual-machines/code/vm-19/vm-19.kql
- docs/content/services/compute/virtual-machines/code/vm-20/vm-20.kql
- docs/content/services/networking/load-balancer/code/lb-2/lb-2.kql
- docs/content/services/storage/storage-Account/_index.md
- docs/content/services/storage/storage-Account/code/st-2/st-2.kql
- docs/content/services/storage/storage-Account/code/st-3/st-3.kql
Added 2 Resource Graph Queries for VMs.
none
none
> VM queries added

- docs/config.toml
With the addition of the WAF category, I am reverting back to priortize sort by weight instead of the title. 
1. Revert previous change to prioritize content sorting by title.
None
> Revert back to prioritize content weight

- docs/content/services/networking/application-gateway/_index.md
- docs/content/services/networking/traffic-manager/_index.md
- docs/themes/ace-documentation/exampleSite/content/shortcodes/buttons.md
Attempt to fix #88 
Everything is still working locally:
1. Fixes issue with traffic manager and the agw queries not showing up in GitHub pages. 
1. None
> Attempt to get Traffic manager and app gateway queries to display again

- docs/content/contributing/_index.md
[AB#31312](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/31312)
Adds ARG query standards to contribution guide
1. Documents the standards in the contribution guide for ARG queries.
1. None
> Document standards for creating ARG queries

- docs/content/services/database/db-for-postgresql/_index.md
- docs/content/services/database/db-for-postgresql/code/psql-1/psql-1.azcli
- docs/content/services/database/db-for-postgresql/code/psql-1/psql-1.kql
- docs/content/services/database/db-for-postgresql/code/psql-1/psql-1.ps1
[AB#29848](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/29848)
Add recommendation for PostgreSQL zone redundancy
1. Add recommendation psql-1
2. Add ARG query for psql-1
1. None
> add recommendation psql-1

- .github/PULL_REQUEST_TEMPLATE.md
[AB#31225](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/31225)
Currently a requirement in PR to link the work items and issues, but not clear where to include them or what keywords to use.
1. Adds clarity for linking work items and issues to PR form
1. None, just text changes to PR form.
> Adds clarity for linking work items and issues to PR form

- docs/content/services/compute/virtual-machine-scale-sets/code/vmss-5/vmss-5.kql
Minor update to VMSS-5 ARG query
[AB#31335](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/31335)
1. update VMSS-5 ARG query to return VMSS instances with autoscale enabled and predictive autoscale disabled
1. None
> update vmss-5 ARG query

- docs/content/services/networking/load-balancer/_index.md
- docs/content/services/networking/load-balancer/code/lb-4/lb-4.kql
Added LB-4 recommendation to identify all Standard Load Balancer(s) that are not zone-redundant.
[AB#29843](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/29843)
1. Adds ARG query for finding Standard Load Balancer(s) without zone-redundancy
N/A
> feat: Added LB with Zone Redundancy

- .github/PULL_REQUEST_TEMPLATE.md
- CODEOWNERS
Increase PR validation requirements from an admin and contributor perspective. 
1. Add codeowners file for ensuring that PRs have validation by particular team members.
2. Add checkbox in PR form to make sure contributors are …
> Adding more requirements for PRs

- docs/content/services/networking/load-balancer/_index.md
- docs/content/services/networking/load-balancer/code/lb-1/lb-1.kql
- docs/content/services/networking/load-balancer/code/lb-1/lb-1.kql.fix
> lb-1 query fixed

- docs/content/services/compute/virtual-machines/code/vm-10/vm-10.kql
- docs/content/services/compute/virtual-machines/code/vm-11/vm-11.kql
- docs/content/services/compute/virtual-machines/code/vm-12/vm-12.kql
- docs/content/services/compute/virtual-machines/code/vm-14/vm-14.kql
- docs/content/services/compute/virtual-machines/code/vm-15/vm-15.kql
- docs/content/services/compute/virtual-machines/code/vm-16/vm-16.kql
- docs/content/services/compute/virtual-machines/code/vm-17/vm-17.kql
- docs/content/services/compute/virtual-machines/code/vm-18/vm-18.kql
- docs/content/services/compute/virtual-machines/code/vm-19/vm-19.kql
- docs/content/services/compute/virtual-machines/code/vm-2/vm-2.kql
- docs/content/services/compute/virtual-machines/code/vm-20/vm-20.kql
- docs/content/services/compute/virtual-machines/code/vm-22/vm-22.kql
- docs/content/services/compute/virtual-machines/code/vm-4/vm-4.kql
- docs/content/services/compute/virtual-machines/code/vm-5/vm-5.kql
- docs/content/services/compute/virtual-machines/code/vm-6/vm-6.kql
- docs/content/services/compute/virtual-machines/code/vm-7/vm-7.kql
- docs/content/services/compute/virtual-machines/code/vm-8/vm-8.kql
- docs/content/services/compute/virtual-machines/code/vm-9/vm-9.kql
In all the available queries in the Virtual Machines section (total 18/22) in APRL, I added "tags" that are associated with the VMs in question by the queries as a column in the results
Adds tags to existing VM queries
[AB#32174](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/32174) 
1. adds tags to VM-2, 4-12, 14-20, 22 query files
> Adding Tags to VM Queries in APRL

- docs/content/services/storage/storage-Account/_index.md
Fixed the language highlight mode for the PowerShell code blocks to `powershell` from `sql` for ST-5, ST-6, ST-7, ST-8.
- None
1. Fixes the language highlight mode for the PowerShell code blocks to `powershell` from `sql` for ST-5, ST-6, ST-7, ST-8.
- None
- **Ensured the changes work fine on my local copy.**
> Fix the language highlight mode for the PowerShell code blocks for ST-5, ST-6, ST-7, ST-8

- docs/content/services/networking/route-table/_index.md
Fixed the language highlight mode for the PowerShell code blocks to `powershell` from `sql` for RT-1, RT-2.
- None
1. Fixes the language highlight mode for the PowerShell code blocks to `powershell` from `sql` for RT-1, RT-2.
- None
- **Ensured the changes works fine on my local copy.**
> Fix the language highlight mode for the PowerShell code blocks for RT-1, RT-2

- docs/content/services/networking/network-security-group/_index.md
Fixed the category of NSG-3 to __Governance__ because it is empty.
- https://azure.github.io/Azure-Proactive-Resiliency-Library/services/networking/network-security-group/#nsg-3---configure-locks-for-network-security-groups-to-avoid-accidental-changes-andor-deletion
- None
1. Fixes the category of NSG-3 to Governance.
- None
> Fix the category of NSG-3

- docs/content/services/security/key-vault/code/kv-2/kv-2.kql
Fixed a query result column of KV-2 to align [the Azure Resource Graph query standards](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing/#azure-resource-graph-arg-queries).
- None
1. Fixes a query result column of KV-2 to `param1` from `enablePurgeProtection`.
- None
> Fix query result column for KV-2

- docs/content/services/networking/virtual-networks/code/vnet-1/vnet-1.kql
Fixed query result columns of VNET-1 to align [the Azure Resource Graph query standards](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing/#azure-resource-graph-arg-queries).
- None
1. Fixes query result columns of VNET-1.
- None
> Fix query result columns for VNET-1

- docs/content/services/networking/virtual-networks/code/vnet-2/vnet-2.kql
Fixed a query result column of VNET-2 to align [the Azure Resource Graph query standards](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing/#azure-resource-graph-arg-queries).
- None
1. Fixes a query result column of VNET-2.
2. Fixes the description of the ARG query.
- None
> Fix query result column for VNET-2

- docs/content/services/security/key-vault/code/kv-1/kv-1.kql
Fixed a query result column of KV-1 to align [the Azure Resource Graph query standards](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing/#azure-resource-graph-arg-queries).
- None
1. Fixes a query result column of KV-1 to `param1` from `softDeleteEnabled`.
- None
> Fix query result column for KV-1

- docs/content/services/compute/virtual-machine-scale-sets/_index.md
- docs/content/services/compute/virtual-machine-scale-sets/code/vmss-2/vmss-2.kql
- docs/content/services/compute/virtual-machine-scale-sets/code/vmss-3/vmss-3.kql
- docs/content/services/compute/virtual-machine-scale-sets/code/vmss-4/vmss-4.kql
- docs/content/services/compute/virtual-machine-scale-sets/code/vmss-9/vmss-9.kql
Updated the KQL for VMSS Recommendations
AB#[32301](https://dev.azure.com/CSUSolEng/Azure%20Infra%20Compute/_workitems/edit/32301)
1.  New KQL for [VMSS-2 - Enable VMSS application health monitoring](https://azure.github.io/Azure-Proactive-Resiliency-Library/services/compute/virtual-machine-scale-sets/#vmss-2---enable-vmss-application-health-monitoring)
2. New KQL for [VMSS-3 - Enable Automatic Repair policy](https://azure.github.io/Azure-Proactive-Resiliency-Library/services/compute/virtual-machine-scale-sets/#vmss-3---enable-automatic-repair-policy)
3. Updated KQL for [VMSS-4 - Configure VMSS Autoscale to custom and configure the scaling metrics](https://azure.github.io/Azure-Proactive-Resiliency-Library/services/compute/virtual-machine-scale-sets/#vmss-4---configure-vmss-autoscale-to-cu …
> Updated KQL for VMSS Recommendations

- docs/content/services/compute/virtual-machines/code/vm-16/vm-16.kql
Added two params to the query result of VM-16. `param1` is disk state, `param2` is the VM name that manages the disk.
- None
1. Adds two params to the query result of VM-16. `param1` is disk state, `param2` is the VM name that manages the disk.
- None
> Add params to VM-16

- docs/content/services/monitoring/log-analytics/code/log-1/log-1.kql
- docs/content/services/monitoring/log-analytics/code/log-3/log-3.kql
- docs/content/services/monitoring/log-analytics/code/log-4/log-4.kql
- docs/content/services/networking/firewall/code/afw-6/afw-6.kql
Fixed `under-development` lines those are not align to [Automation Standards for Recommendations](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing/#automation-standards-for-recommendations).
- None
1. Fixes non-standard `under-development` lines.
- None
- Build succeeded and showing contents correctly with local server (`hugo server -D`).
> Fix non-standard "under-development" lines

- docs/content/services/compute/virtual-machines/code/vm-18/vm-18.kql
Improved the VM-18 query.
- #194
- #195
1. Changes `param1` value to `policyAssignmentName` from `name`. (#194)
2. Aggregates "where" operators based on [Best practices for Kusto Query Language queries](https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/best-practices).
3. Adds policy definition name and ID as params (`param2`, `param3`).
4. Fixes the `tags` column in the result (#195) 
- None
> Improve VM-18 query

- docs/content/services/compute/virtual-machines/_index.md
- docs/content/services/container/container-registry/_index.md
- docs/content/services/integration/event-grid/_index.md
- docs/content/services/networking/network-security-group/_index.md
- docs/content/services/storage/storage-Account/_index.md
Changed the recommendation title wording of diagnostics settings from `for all Azure Resources` to specific resource type.
- #167
1. Changes the recommendation title wording of diagnostics settings from `for all Azure Resources` to specific resource type.
2. Changes the recommendation title of VM-21 to match with other resource's recommendation title of the same diagnostics settings.
- None
- Document building is fine in my local environment.
> Change the recommendation title wording of diagnostics settings

- docs/content/services/networking/expressroute-gateway/_index.md
- docs/content/services/networking/expressroute-gateway/code/ergw-4/ergw-4.kql
Fix ERGW-4 link at top of doc by removing white space
AB#32703
1. Fixes broken link at top of doc for ERGW-4, due to whitespace
- [x ] Performed testing and provided evidence …
> Fix ERGW-4 link

- services-abbreviations.csv
The queries for AKS are not getting executed, as the service is missing in the service list.
None
1. execute the queries for AKS as well
None
> (fix) add missing aks to service list

- CODEOWNERS
Add aprl-networking team to codeowners file so that they are automatically added to PR pertaining to all networking recommendations.
NA
1. Adds the ability for networking team to be able to automatically add reviewers and require review from someone within their team if it is networking specific.
1. N/A
> Add networking team responsibility to PRs

- docs/content/services/networking/expressroute-circuits/_index.md
- docs/content/services/networking/expressroute-circuits/code/erc-1/erc-1.kql
- docs/content/services/networking/expressroute-circuits/code/erc-3/erc-3.kql
- docs/content/services/networking/expressroute-circuits/code/erc-7/erc-7.kql
- docs/content/services/networking/expressroute-circuits/code/erc-8/erc-8.kql
- docs/content/services/networking/expressroute-circuits/code/erc-9/erc-9.kql
Modify APRL ERC guidance to align with current ER resiliency efforts
AB#32736
- Rewrite ERC-2 to cover ERC-3 and ERC-4
- Remove ERC-3 and ERC-4
- Rewrite ERC-1 title to be more specific, and renumber to ERC-3
- Rewrite ERC-8 to align with current effort around 2+ ER circuits per ER gateway, removing geo-redundant wording. Renumber to ERC-1, change Impact to High (from Medium)
- Rewrite ERC-9 to align with current effort, in such a way the S2S VPN as an ER circuit backup is an interim measure until a second ER circuit is in place. Renumber to ERC-7
- Minor typo corrections, expansion of ER acronym to ExpressRoute in some areas.
> Rewrite and re-order APRL ERC guidance to align with Jan 2024 ER resiliency efforts

- docs/content/services/specialized-workloads/azure-virtual-desktop/_index.md
- docs/content/services/specialized-workloads/azure-virtual-desktop/code/avd-9/avd-9.kql
I added a 9th recommendation per request of the PG and Pm. I thought there may be push back because it is on a storage account and we have a storage account section bu they felt like FSLogix needed its own recommendation.  I agree with the AVd team and this this is important. Happy to discuss further if you fell like it does not belong in this section. 
[Replace this with a list of related GitHub Issues and/or ADO Work Items (Internal Only)](https://dev.azure.com/CSUSolEng/Accelerator%20-%20AVD/_workitems/edit/32444)
- To associate an ADO Work Item, use …
> Added AVD recommendation 9

- docs/content/services/database/redis-cache/code/redis-1/redis-1.kql
add tags to redis cache query
[AB#32779](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/32779)
1. redis-1.kql
> Add tags to Redis Cache ARG query

- docs/content/services/networking/virtual-networks/_index.md
- docs/content/services/networking/virtual-networks/code/vnet-1/vnet-1.kql
vnet-1 KQL needs to exclude GatewaySubnet as applying NSG on GatewaySubnet is not supported.
[GatewaySubnet](https://learn.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-about-vpn-gateway-settings#gwsub)
#256
> Vnet 1 fix

- docs/content/services/integration/event-grid/_index.md
Metadata for Powershell scripts indicates `sql` instead of `powershell` like all other Powershell scripts.
Closes #279 
n.a.
> Closes #279 (Metadata for Powershell scripts indicates sql instead of powershell like all other Powershell scripts)

- docs/content/Privacy/_index.md
Lowering weight of Privacy page to be on bottom of navigation pane.
N/A
1. Lowering weight of Privacy page to be on bottom of navigation pane.
None
> Lowering weight of privacy page

- docs/content/services/networking/application-gateway/code/agw-9/agw-9.kql
KQL for agw-9 - Ensure Application Gateway Subnet is using a /24 subnet mask.  This initially said could not be validated, so either some property changed or I'm grossly misunderstanding the recommendation.  The query is hard coded to look at the first index of gatewayIPConfiguration for the subnet id, but I don't think it's possible to associate more than one subnet with a single app gateway.  If I'm incorrect here, I can adjust the query. 
N/A
1. agw-9 KQL
NA
> agw-9 Ensure Application Gateway Subnet is using a /24 subnet mask

- docs/content/well-architected/4-deploy/_index.md
rosanto - Updating WADP-2 content which was missing.
rosanto - Updating WADP-2 content which was missing.
rosanto - Updating WADP-2 content which was missing.
- [ x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [ x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [ x] Performed …
> rosanto - Updating WADP-2 content which was missing.

- docs/content/services/database/db-for-mysql/_index.md
- docs/content/services/database/db-for-mysql/code/mysql-1/mysql-1.kql
- docs/content/services/database/db-for-mysql/code/mysql-2/mysql-2.kql
- docs/content/services/database/db-for-postgresql/_index.md
- docs/content/services/database/db-for-postgresql/code/psql-2/psql-2.kql
N.A
1. Update to psql-2.kql provided query for custom maint window
2. Update to myql-1.kql provided query for Zone redundant HA
3.  Update to myql-2.kql provided query for custom maint window
4.  Update to db-for-postgresql/_index.md set ARG Query available for  psql-2
5.  Update to db-for-mysql/_index.md set ARG Query available for  myql-1 and myql-2
- [ x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- …
> Oss resource graph queries

- docs/content/services/compute/virtual-machine-scale-sets/_index.md
New recommendations were added to VMSS page as well as ARG's for all recommendations however summary table was still showing some recommendations not having ARG
1. Virtual-machine-scale-sets _index.md summary table
> Updated VMSS Summary Table w/ARG Availability

- docs/content/services/specialized-workloads/azure-vmware-solution/_index.md
- docs/content/services/specialized-workloads/azure-vmware-solution/code/avs-1/avs-1.kql
- docs/content/services/specialized-workloads/azure-vmware-solution/code/avs-2/avs-2.ps1
Adds back AVS-1 and AVS-2 recommendations.  Includes a kusto query for AVS-1, and a powershell script for AVS-2
1. Adds AVS-1 and AVS-2 Recommendation text
2. Creates a kusto query for AVS-1
3. Creates a powershell query for AVS-2
1. None
> Adding back AVS-1 and 2 with kusto and powershell queries

- docs/content/services/integration/event-hub/_index.md
- docs/content/services/integration/event-hub/code/evhns-2/evhns-2.kql
EVHNS-2 KQL - Enable auto-inflate on Event Hub Standard tier
N/A
1. Adds kql file for event hub namespace recommendation 2
> evhns-2 kql -  Enable auto-inflate on Event Hub Standard tier

- docs/content/services/compute/virtual-machines/code/vm-1/vm-1.kql
Update to VM-1 query
None
1. Update query to account for empty properties.virtualMachineScaleSet object
1. None
> update vm-1 query

- docs/content/services/compute/virtual-machines/_index.md
Fix VM-25 query availability as no query is available.
N/A
1. Fixes query availability field for Vm-25
None
> Correct VM-25 query availability

- docs/content/services/container/container-registry/_index.md
- docs/content/services/container/container-registry/code/cr-4/cr-4.kql
Removed CR-4 since it is not applicable to resiliency and re-numbered items. No query changes.
1. Removes CR-4
2. Re-numbers CR items - it looked like the numbering was off by one before I did the removal so some of them changed by 2 places instead of one place.
None
> ACR: Remove CR-4 and re-number CR items

- docs/content/services/networking/expressroute-direct/code/erd-1/erd-1.kql
- docs/content/services/networking/expressroute-direct/code/erd-2/erd-2.kql
Wrote Azure Resource Graph Query to Find all Express Route Directs that do not have Admin State of both Links Enabled
NA
1. Adds Azure Resource Graph Query to Find all Express Route Directs that do not have Admin State of both Links Enabled
NA
> Update erd-1.kql & erd-2.kql

- docs/content/services/management/subscription/_index.md
Removed the duplicated link in the Resources section of [MS-1](https://azure.github.io/Azure-Proactive-Resiliency-Library/services/management/subscription/#ms-1---do-not-create-more-than-2000-citrix-vda-servers-per-subscription). Those have the same link text, but the link URL is the same.
None
1. Removes the duplicated link in the Resources section of MS-1.
None
- Confirmed that document build succeeded on my local machine.
> MS-1: Remove duplicated resource link

- docs/content/services/storage/azure-netapp-files/_index.md
- docs/content/services/storage/azure-netapp-files/code/anf-6/anf-6.kql
- docs/content/services/storage/azure-netapp-files/code/anf-7/anf-7.kql
Found a small typo changed "zone" -> "region".
Updated and tested KQL for ANF-6 and ANF-7. Previous KQL was showing positive results instead of negative results.
n/a
1. one small typo to _index
2. anf-6.kql
3. anf-7.kql
n/a
> fixed typo and updated KQL issues

- docs/content/services/networking/application-gateway/code/agw-9/agw-9.kql
Fixes the recommendation id in the query.
none
> agw-9 - fixes recommendation id

- docs/content/services/networking/application-gateway/_index.md
- docs/content/services/networking/application-gateway/code/agw-7/agw-7.kql
- docs/content/services/networking/application-gateway/code/agw-7/agw-7.kql.fix
Creates agw-7 recommendation for zone-redundant Application Gateway deployment
1. add agw-7 recommendation with resource graph query
none
> agw-7 check for AppGw deployed in multiple Zones

- docs/content/services/networking/expressroute-gateway/code/ergw-1/ergw-1.kql
- docs/content/services/networking/expressroute-gateway/code/ergw-4/ergw-4.1.kql
- docs/content/services/networking/expressroute-gateway/code/ergw-4/ergw-4.2.kql
- docs/content/services/networking/expressroute-gateway/code/ergw-4/ergw-4.3.kql
- docs/content/services/networking/expressroute-gateway/code/ergw-4/ergw-4.4.kql
- docs/content/services/networking/expressroute-gateway/code/ergw-4/ergw-4.5.kql
- docs/content/services/networking/expressroute-gateway/code/ergw-4/ergw-4.6.kql
- docs/content/services/networking/expressroute-gateway/code/ergw-4/ergw-4.7.kql
- docs/content/services/specialized-workloads/azure-vmware-solution/code/avs-1/avs-1.kql
- docs/content/services/specialized-workloads/azure-vmware-solution/code/avs-3/avs-3.kql
- docs/content/services/specialized-workloads/azure-vmware-solution/code/avs-5/avs-5.kql
- docs/content/services/specialized-workloads/azure-vmware-solution/code/avs-6/avs-6.kql
This pull request contains fixes for ERGW-1, ERGW-4, AVS-1, AVS-3, AVS-5, and AVS-6 ARG kusto queries.  It corrects an issue where certain id string used in kusto join statements had case mismatches causing incomplete or inaccurate results.  This PR updates the relevant kusto queries to force all fields used in a join statement to first be cast to lower case.
closes #425 
- AVS bug 34512 (ADO)
- #425 
1. ERGW-1, ERGW-4, AVS-1, AVS-3, AVS-5, and AVS-6 ARG kusto queries.
No Breaking Changes.
- [ x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [ x] Checked for duplicate [Pull …
> corrected join failures due to case mismatch
